# Import Libraries

In [0]:
import numpy as np
import matplotlib.pyplot as pt
import pandas as pd

# importing datasheet

In [0]:
datasheet = pd.read_excel('TableLibrary.xlsx')
X = datasheet.iloc[:,:-1].values
Y = datasheet.iloc[:,-1].values

In [40]:
print(X)

[['Public 4-year' nan 6527266.0]
 ['Public 2-year' 3689366.0 nan]
 ['Public less-than-2-year' nan 44024.0]
 ['Private nonprofit 4-year' 3498999.0 2616367.0]
 ['Private nonprofit 2-year' 52481.0 nan]
 ['Private nonprofit less-than-2-year' 9551.0 9551.0]
 ['Private for-profit 4-year' nan 547974.0]
 ['Private for-profit 2-year' 242795.0 nan]
 ['Private for-profit less-than-2-year' nan 236013.0]]


In [41]:
print(Y)

[999343      0      0 882632     14      0 195338      0      0]


# Taking care of Missing Data

In [0]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:])
X[:,1:] = imputer.transform(X[:,1:])

In [43]:
print(X)

[['Public 4-year' 1498638.4 6527266.0]
 ['Public 2-year' 3689366.0 1663532.5]
 ['Public less-than-2-year' 1498638.4 44024.0]
 ['Private nonprofit 4-year' 3498999.0 2616367.0]
 ['Private nonprofit 2-year' 52481.0 1663532.5]
 ['Private nonprofit less-than-2-year' 9551.0 9551.0]
 ['Private for-profit 4-year' 1498638.4 547974.0]
 ['Private for-profit 2-year' 242795.0 1663532.5]
 ['Private for-profit less-than-2-year' 1498638.4 236013.0]]


# Encoding Catagory












## Encoding Independent Variable

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [61]:
print(X)

[[7 1498638.4 6527266.0]
 [6 3689366.0 1663532.5]
 [8 1498638.4 44024.0]
 [4 3498999.0 2616367.0]
 [3 52481.0 1663532.5]
 [5 9551.0 9551.0]
 [1 1498638.4 547974.0]
 [0 242795.0 1663532.5]
 [2 1498638.4 236013.0]]


## Encoding dependent variable.
We do not want to do any encoding for the dependent vafriable

# Spliting the data into training set and test set

In [0]:
from sklearn.model_selection import train_test_split
X_Tran, X_Test, Y_Tran, Y_Test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [65]:
print(X_Tran)

[[1 1498638.4 547974.0]
 [0 242795.0 1663532.5]
 [6 3689366.0 1663532.5]
 [7 1498638.4 6527266.0]
 [3 52481.0 1663532.5]
 [4 3498999.0 2616367.0]
 [5 9551.0 9551.0]]


In [66]:
print(Y_Tran)

[195338      0      0 999343     14 882632      0]


In [67]:
print(X_Test)

[[2 1498638.4 236013.0]
 [8 1498638.4 44024.0]]


In [68]:
print(Y_Test)

[0 0]


# Feature Scalling

In [0]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_Tran=sc.fit_transform(X_Tran)
X_Test=sc.fit_transform(X_Test)

In [70]:
print(X_Tran)

[[-1.14366560e+00 -1.60741551e-16 -7.86490603e-01]
 [-1.56501609e+00 -8.67008795e-01 -2.20750984e-01]
 [ 9.63086825e-01  1.51243387e+00 -2.20750984e-01]
 [ 1.38443731e+00 -1.60741551e-16  2.24582225e+00]
 [-3.00964633e-01 -9.98397718e-01 -2.20750984e-01]
 [ 1.20385853e-01  1.38100836e+00  2.62465473e-01]
 [ 5.41736339e-01 -1.02803572e+00 -1.05954417e+00]]


In [71]:
print(X_Test)

[[-1.  0.  1.]
 [ 1.  0. -1.]]
