# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Part 1

## Import dataset

In [2]:
dataset= pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


## Catagorical data

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [6]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One hat encoding in the geography column

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Split the dataset into training set and testset

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
print(x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [11]:
print(x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [12]:
print(y_train)

[0 0 0 ... 0 0 1]


In [13]:
print(y_test)

[0 1 0 ... 0 0 0]


## Feature Scalling

In [14]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [16]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# Part2 - Building the ANN

## Initializing the ANN

In [17]:
ann=tf.keras.models.Sequential()

## Adding the input layers and adding the first hidden layers

In [18]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding output layers

In [20]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Part3 - Train the ANN

## Compile the ANN

In [21]:
ann.compile(optimizer ='adam' ,loss ='binary_crossentropy' , metrics =['accuracy'])

## Training the ANN on the training set

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5613 - accuracy: 0.7305
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4653 - accuracy: 0.7964
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4450 - accuracy: 0.8006
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4377 - accuracy: 0.8041
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4333 - accuracy: 0.8041
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4298 - accuracy: 0.8074
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8104
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.8136
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4155 - accuracy: 0.8152
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4090 - accura

# Part4 - making the predection and evaluate the model

## Predecting the result of a single observation

In [25]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,5000]])))

[[0.02257384]]


## Predict the test result

In [27]:
y_pred = ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the confusion matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1538   57]
 [ 213  192]]


0.865